Server:
  port: 8488
spring:
  application:
    name: APIClient

  datasource:
#    doris: #Doris
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.130:9030/doris_data
    username: root
    password:
